version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: interactive-qa-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongodb_password_123
      MONGO_INITDB_DATABASE: interactive_qa_db
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - interactive-qa-network

  redis:
    image: redis:7.2-alpine
    container_name: interactive-qa-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redis_password_123
    volumes:
      - redis_data:/data
    networks:
      - interactive-qa-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  redis_data:
    driver: local

networks:
  interactive-qa-network:
    driver: bridge